version: '3'

services:
  db_dev:
    image: 'postgres:14.5'
    command: [ "postgres", "-c", "wal_level=logical" ]
    environment:
      POSTGRES_USER: depeche
      POSTGRES_PASSWORD: depeche
      POSTGRES_DB: depeche_test
    ports:
      - 4888:5432
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'es']
      timeout: 15s
      interval: 5s
      retries: 10
