version: '3'

services:
  db_dev:
    image: 'postgres:${POSTGRES_VERSION:-17}'
    environment:
      POSTGRES_USER: depeche
      POSTGRES_PASSWORD: depeche
      POSTGRES_DB: depeche_demo
    ports:
      - 4888:5432
    restart: unless-stopped
