strict: true
site_name: Depeche DB
repo_name: depeche-py/depeche-db
repo_url: https://github.com/depeche-py/depeche-db
copyright: Copyright &copy; 2023 Martin Vielsmaier
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/depeche-py/depeche-db/
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/depeche-db/
nav:
  - Home: index.md
  - Getting started:
      - Installation: getting-started/installation.md
      - Writing & reading messages: generated/output/getting-started-write-read.md
      - Aggregated streams: generated/output/getting-started-aggregated-stream.md
      - Subscription: generated/output/getting-started-subscription.md
      - Executor: getting-started/executor.md
  - Concepts:
    - Data model: concepts/data-model.md
    - Subscriptions: concepts/subscriptions.md
plugins:
  - mermaid2:
      version: 9.3.0
  - search
  - diagrams
  - alias
  - macros
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: light green
  features:
    - navigation.expand
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
