strict: true
site_name: Depeche DB
nav:
  - Home: index.md
  - Getting started:
      - Installation: getting-started/installation.md
      - Writing & reading messages: generated/output/getting-started-write-read.md
      - Aggregated streams: generated/output/getting-started-aggregated-stream.md
      - Subscription: generated/output/getting-started-subscription.md
      - Executor: getting-started/executor.md
  - Concepts:
    - Data model: concepts/data-model.md
    - Subscriptions: concepts/subscriptions.md
plugins:
  - mermaid2:
      version: 9.3.0
  - search
  - diagrams
  - alias
  - macros
theme:
  name: material
  features:
    - navigation.expand
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
